### ISSUE TITLE
Read a dsn file and generate a svg file

### ISSUE THREAD

**Issue by aicha11** [john681611/INF_LandingPage#19]
Hello,

I have three files : 
design.dsn : it contains the instruction for example 
                            ( POSITION: 200, 200
                            CIRCLE: 5 5 2
                             LINE: position 300, 350 ) 

canvas.svg : the generated file
main.js : read from file design.dsn and generate the svg file.

Can anyone tell me how can I read from dsn file and write the instruction (dsn file) into svg file?

Thanks in advance.

**Comment by john681611** [comment]
This evidently has nothing to do with this repo.
Try https://stackoverflow.com/
